export const PROGRAMS = [
  {
    id: "hypertrophy",
    name: "Helix Hypertrophy",
    days: 4,
    vibe: "cool",
    blurb: "Push / pull / legs / upper. Volume that actually recovers.",
    exercises: [
      { name: "Barbell Bench Press", sets: 4, reps: "6–8" },
      { name: "Incline Dumbbell Press", sets: 3, reps: "8–10" },
      { name: "Weighted Dips", sets: 3, reps: "8–12" },
      { name: "Cable Lateral Raise", sets: 4, reps: "12–15" },
      { name: "Overhead Triceps Extension", sets: 3, reps: "10–12" },
    ],
  },
  {
    id: "iron",
    name: "Iron Circuit",
    days: 3,
    vibe: "warm",
    blurb: "Compound strength with a short metabolic finisher.",
    exercises: [
      { name: "Back Squat", sets: 5, reps: "5" },
      { name: "Romanian Deadlift", sets: 3, reps: "6–8" },
      { name: "Pull-Up", sets: 4, reps: "AMRAP" },
      { name: "Farmer Carry", sets: 4, reps: "40m" },
    ],
  },
  {
    id: "first-light",
    name: "First Light",
    days: 3,
    vibe: "",
    blurb: "Beginner full-body. Learn the pattern, earn the load.",
    exercises: [
      { name: "Goblet Squat", sets: 3, reps: "10" },
      { name: "Dumbbell Bench Press", sets: 3, reps: "10" },
      { name: "Lat Pulldown", sets: 3, reps: "10" },
      { name: "Hip Hinge / RDL", sets: 3, reps: "10" },
      { name: "Plank", sets: 3, reps: "30s" },
    ],
  },
  {
    id: "engine",
    name: "Engine Day",
    days: 1,
    vibe: "warm",
    blurb: "Conditioning that still respects lifting legs.",
    exercises: [
      { name: "Row Erg", sets: 1, reps: "8 min easy" },
      { name: "Kettlebell Swing", sets: 5, reps: "15" },
      { name: "Air Bike Intervals", sets: 8, reps: "20s on / 40s off" },
      { name: "Walking Lunge", sets: 3, reps: "20 steps" },
    ],
  },
  {
    id: "pull",
    name: "Pull Architecture",
    days: 1,
    vibe: "cool",
    blurb: "Lats, posterior chain, grip. Build the back that holds the rest.",
    exercises: [
      { name: "Weighted Pull-Up", sets: 4, reps: "5–8" },
      { name: "Barbell Row", sets: 4, reps: "6–8" },
      { name: "Chest-Supported Row", sets: 3, reps: "10" },
      { name: "Face Pull", sets: 3, reps: "15" },
      { name: "Hammer Curl", sets: 3, reps: "10" },
    ],
  },
  {
    id: "trail-mix",
    name: "Trail Mix",
    days: 1,
    vibe: "",
    blurb: "Hybrid: posterior strength then a zone-2 closer.",
    exercises: [
      { name: "Trap Bar Deadlift", sets: 4, reps: "5" },
      { name: "Split Squat", sets: 3, reps: "8/side" },
      { name: "Calf Raise", sets: 3, reps: "12" },
      { name: "Easy Run / Bike", sets: 1, reps: "25–40 min Z2" },
    ],
  },
];

export const EXERCISE_BANK = [
  "Barbell Bench Press",
  "Incline Dumbbell Press",
  "Overhead Press",
  "Back Squat",
  "Front Squat",
  "Romanian Deadlift",
  "Conventional Deadlift",
  "Trap Bar Deadlift",
  "Barbell Row",
  "Pull-Up",
  "Lat Pulldown",
  "Hip Thrust",
  "Bulgarian Split Squat",
  "Dumbbell Curl",
  "Triceps Pushdown",
  "Face Pull",
  "Lateral Raise",
  "Plank",
  "Farmer Carry",
];
